data class Post(
    val id: Long = 0,
    val authorId: Long = 0,
    val author: String = "",
    val authorJob: String? = null,
    val authorAvatar: String? = null,
    val content: String = "",
    val published: String = "01-01-1970",
    val coords: Coordinates? = null,
    val link: String? = null,
    val mentionedMe: Boolean = false,
    val likedByMe: Boolean = false,
    val attachment: Attachment? = null,
    val likeOwnerIds: List<Long> = emptyList(),
    val users: Map<Long, UserPreview> = emptyMap(),
    val mentionIds: List<Long> = emptyList(),
)
